// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/features/profile/logic/bloc/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile/features/auth/data/models/user_info.dart' as _i2;
import 'package:mobile/features/profile/data/dto/update_profile_request.dart'
    as _i5;
import 'package:mobile/features/profile/data/repositories/i_profile_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserInfo_0 extends _i1.SmartFake implements _i2.UserInfo {
  _FakeUserInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRepository extends _i1.Mock
    implements _i3.IProfileRepository {
  MockIProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserInfo> getMyProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getMyProfile, []),
            returnValue: _i4.Future<_i2.UserInfo>.value(
              _FakeUserInfo_0(this, Invocation.method(#getMyProfile, [])),
            ),
          )
          as _i4.Future<_i2.UserInfo>);

  @override
  _i4.Future<_i2.UserInfo> updateProfile(_i5.UpdateProfileRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [request]),
            returnValue: _i4.Future<_i2.UserInfo>.value(
              _FakeUserInfo_0(
                this,
                Invocation.method(#updateProfile, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.UserInfo>);

  @override
  _i4.Future<_i2.UserInfo> updateProfilePicture(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePicture, [imagePath]),
            returnValue: _i4.Future<_i2.UserInfo>.value(
              _FakeUserInfo_0(
                this,
                Invocation.method(#updateProfilePicture, [imagePath]),
              ),
            ),
          )
          as _i4.Future<_i2.UserInfo>);
}
